<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <FileVersion>2.1.2</FileVersion>
        <TargetFramework>net9.0</TargetFramework>
        <RepositoryUrl>https://github.com/Emik03/Emik.Manual</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Emik03/Emik.Manual</PackageProjectUrl>
        <Description>Library to programmatically create manual .apworld files.</Description>
        <PackageTags>Archipelago MultiWorld MW Manual Multigame Multi Game Randomizer Generation APWorld AP World</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="$(Morsels)/Compile/**/*.cs"/>
        <PackageReference Include="Emik.Analyzers.Matches" Version="1.3.3"/>
    </ItemGroup>
</Project>
